### ISSUE TITLE
Airway-Segmentation on Slicer 1.4.5 doesn't work anymore

### ISSUE THREAD

**Issue by eyrinck** [PietroNardelli/Slicer-AirwaySegmentation#3]
Dear Pietro Nardelli,
The former version with three fiducial points works very good in the past. I updated Slicer and the AirwaySegmentation module yesterday.
Now only the cli module works with one fiducial in the trachea but ends up on the main bifurcation, no main bronchi etc. are recognized.

The script AirwaySegmentation gives back the following error:

Traceback (most recent call last):
  File "D:/Users/xxx/AppData/Roaming/NA-MIC/Extensions-24735/Slicer-AirwaySegmentation/lib/Slicer-4.5/qt-scripted-modules/AirwaySegmentation.py", line 163, in onApplyButton
    self.labelNode.SetLabelMap(1)
AttributeError: SetLabelMap

Can you help?

**Comment by adamsonn** [comment]
I am getting the same problem as eyrinck. Clicking the apply button just makes the program run indefinitely with no result. This is on slicer 4.5.1, is there a version that works better with this extension?

**Comment by PietroNardelli** [comment]
Hi guys,

I think that I found the bug. It should be fixed now and you should have it
up and running tomorrow on the nightly build version!

Thanks for that and sorry for the trouble!

**Comment by eyrinck** [comment]
Sorry to say, the script works now without error, but the model (tested with two different ct-scans 1mm slices) ends up in the trachea and segments no main bronchi.

**Comment by adamsonn** [comment]
I am still having issues as well. When I run the airway segmentation module, I get a volume file called airwaylabel, but I am unable to produce a 3D rendering of it. The python script  I am running build 4.5.0-2016-06-22. Pietro all your help is much appreciated!

**Comment by PietroNardelli** [comment]
Hi guys,

I'm going on vacation this week! I'll have to look into it next week!!
Sorry about that! I really don't know what is going on with slicer at this
point, as it works fine with my versions of Slicer!!! Can you just send me
info about the OS you are using?

Best regards,
Pietro

**Comment by adamsonn** [comment]
I am running windows 7 service pack 1.Which OS are you using and which version of slicer do you have working with your airwaysegmentation? I have access to a few different machines and can try. Please enjoy your vacation and I will leave you alone this week!

**Comment by eyrinck** [comment]
I tested it on 64bit Windows 7 SP 1 and now after Upgrading on Windows 10 Version 1511. Intel I5, 16GB RAM, NVIDIA graphics Geforce GTX 660.

**Comment by adamsonn** [comment]
Slicer 4.5.0-2016-06-22

Mac Tested
OS X El Capitan 
Processor 2.7 GHz intel core i5
Memory 8 GB 1600 MHz DDR3

Windows Tested
Windows 7 SP1 64-bit
intel core i5 1.70 GHz 1.70GHz
Memory 8 GB 

Linux Tested
Ubuntu 16.04 LTS 64 bit
Memory 1.9GiB
Pentium dual core 2.70GHz

All receive the same problem. I load the Dicom, downloaded from Cornell's database, go to the volume module click CT-Lung, place a Fiducial point in the trachea, then run airway segmentation module. Module produces no thresholded images, but produces a new volume called Airway label that I cannot render. I get the same result on every OS

Slicer Python Interactor says the same thing
>>>Run the algorithm 
Running the algorithm 
I have let it run for 5+ minutes with no change

**Comment by PietroNardelli** [comment]
Hi guys,

thanks for the info! The issues are probably due to the fact that the
extension was not recognizing your cases for finding a good threshold. I
have now made it more general, and you should have it available with the
new nightly build. However, bare in mind that without having your cases
available I cannot properly optimize the threshold. At the moment I am just
providing a "guess" of what might be expected. If you are happy to share
your cases I can work to find the optimal threshold for those cases,
otherwise I am afraid you will have to do it yourself, and then update the
extension in 3D Slicer.

Thanks a lot for your very important feedback!

Pietro

2016-06-28 8:53 GMT-04:00 adamsonn notifications@github.com:

**Comment by eyrinck** [comment]
Dear Pietro,
tested it with the new version. Sorry, see yourself.
![airway](https://cloud.githubusercontent.com/assets/15895624/16777486/0aa1321e-486a-11e6-8417-5afd2082d539.jpg)

**Comment by PietroNardelli** [comment]
Yes, the Slicer guys have not given me the OK for the updated version yet!
Sorry about that!

2016-07-12 13:54 GMT-04:00 eyrinck notifications@github.com:

**Comment by adamsonn** [comment]
I can't replicate the result that eyrinck gets. I think it may be a problem with my file. I am using a file from Cornell's data base, but it is old and from the year 2000. You guys can download my file bellow but can someone upload a working Dicom file to the website bellow to confirm that it is a file problem on my end? You can use the website www.dicomlibrary.com

http://www.dicomlibrary.com/?manage=9bd238957e0626a4d850a0fd94b13965

http://www.dicomlibrary.com/?manage=9bd238957e0626a4d850a0fd94b13965&multiple=true

**Comment by PietroNardelli** [comment]
I am trying to download the file at the link but it doe not let me! All I
get is a blank webpage!

2016-07-12 14:46 GMT-04:00 adamsonn notifications@github.com:

**Comment by adamsonn** [comment]
tar.gz
https://drive.google.com/open?id=0B12TS1PH6H6QMDRFOEtSWWY3dmc

.zip
https://drive.google.com/open?id=0B12TS1PH6H6QY0d2cmEtSVJ0aFE

Hopefully this works sorry for the blank page

**Comment by PietroNardelli** [comment]
That works thanks! The problem with your data is that it does not contain
any information about the reconstruction kernel that has been used to
reconstruct the image, so you cannot use the Airway Segmentation module!
You can try using the Airway Segmentation CLI module instead. Just to see
if it works, type STANDARD in the Kernel Type section (after placing the
fiducial point in the trachea and selecting the airway label map in the
specific section!). It works for me! Let me know if it works for you too!

Thanks

2016-07-12 15:01 GMT-04:00 adamsonn notifications@github.com:

**Comment by adamsonn** [comment]
![image](https://cloud.githubusercontent.com/assets/20114801/16780362/5c7e4db8-4844-11e6-876a-0d54de613706.png)

It works!

Thank you!!!

**Comment by PietroNardelli** [comment]
Great! I am glad that it finally works for you! Unfortunately, results do
not seem optimal for your case. If you could find out the proper kernel
perhaps you will get better results. The alternative is to use cases with a
better resolution!

2016-07-12 15:22 GMT-04:00 adamsonn notifications@github.com:

**Comment by eyrinck** [comment]
It works :-)
Thank you very much for your work!

![airway](https://cloud.githubusercontent.com/assets/15895624/16895512/e66251d2-4b78-11e6-872f-471765e7f52e.jpg)

**Comment by PietroNardelli** [comment]
Great, I'm glad it worked!! Keep the comments/feedback coming so I can
continue improving the module!!

Thanks,
Pietro

2016-07-16 11:16 GMT-04:00 eyrinck notifications@github.com:

**Comment by ashlyshaji** [comment]
Dear Pietro
I am new to 3d slicer . I am trying to generate airway segment from CT DICOM images using Airway Segmentation Module . But only the location of seed point is getting generated in 3d viewer, instead of the whole airway.
OS : Linux
Version : slicer 4.8
I have attached the screenshot ,showing the output and also the parameters I have given.
Could  you help?

![screenshot](https://user-images.githubusercontent.com/34036397/33279555-3667469c-d39f-11e7-9ccf-f12c4b91b61a.png)

Best Regards
Ashly

**Comment by PietroNardelli** [comment]
Hi Ashly,

Let me check and see if I can replicate the same error. What OS are you using?

Thanks a lot,
Pietro

**Comment by ashlyshaji** [comment]
Hi,

I am using openSuse Tumbleweed. I also tried the extension in windows 10
OS. Both are showing same issues.

Best Regards,
Ashly

**Comment by PietroNardelli** [comment]
And did you try with other images? Do you always have the same issue? I just tried the extension with the new Slicer 4.8 and it works fine for me.

**Comment by ashlyshaji** [comment]
Yes i tried with 3 different image sets. None of them worked for me. Are
there any library files which i need to use with the extension?


Regards,
Ashly

**Comment by PietroNardelli** [comment]
This is weird. Did you install the stable release version of Slicer from the website? How did you install the extension?

**Comment by ashlyshaji** [comment]
I installed it from the extension Manager in 3D slicer.

Regards,
Ashly

**Comment by ashlyshaji** [comment]
And yes, I  installed the stable version from slicer website.

**Comment by PietroNardelli** [comment]
Can you check the error panel (Ctrl-e) and see if it reports any error?

**Comment by ashlyshaji** [comment]
Hello Pietro,
I have attached the error log .
Please see to it.
Regards
Ashly

**Comment by ashlyshaji** [comment]
I also used another set of DICOM files ,downloaded from below  link.
tar.gz

https://drive.google.com/open?id=0B12TS1PH6H6QMDRFOEtSWWY3dmc

.zip
https://drive.google.com/open?id=0B12TS1PH6H6QY0d2cmEtSVJ0aFE

But still ,its not working .

Regards

**Comment by PietroNardelli** [comment]
It is true that the AirwaySegmentation module does not work...but the Airway Segmentation CLI works well for me with the data you sent! Can you try with that?

**Comment by ashlyshaji** [comment]
I tried with Airway Segmentation CLI only.
![screenshot](https://user-images.githubusercontent.com/34036397/33326513-74309922-d455-11e7-90a6-02bf52a7918b.png)

**Comment by PietroNardelli** [comment]
But that is not the data you sent right?

**Comment by ashlyshaji** [comment]
![screenshot](https://user-images.githubusercontent.com/34036397/33326612-b6b2dd5a-d455-11e7-8872-3f9e1bd05a0b.png)

**Comment by PietroNardelli** [comment]
I don't think the CT you are using in the image you attached is the same you sent me to try...can you try with that and check if with that CT it works for you? Thanks

**Comment by ashlyshaji** [comment]
Im sorry ...that was the one 1 tried first.

![image](https://user-images.githubusercontent.com/34036397/33326900-7df666de-d456-11e7-9ae5-aee87dba0212.png)

 For this ,I used the downloaded data from the given link .

**Comment by PietroNardelli** [comment]
OK, so for this case the CLI module works, as it is not supposed to automatically create the 3D model, but it created the label map! I will investigate to see why the AirwaySegmentation module (that should create the 3D module) does not work!

**Comment by ashlyshaji** [comment]
Ok..Thank you so much  .

This is the error report I got and it says **"Airway Segmentation CLI completed without errors"** , but I am not getting any segmentation in 3d viewer. So ,should i change any settings of 3d Viewer ?

C:/Users/sh/AppData/Roaming/NA-MIC/Extensions-26489/Slicer-AirwaySegmentation/lib/Slicer-4.8/cli-modules/AirwaySegmentationCLI.exe --labelValue 2 --seed 4.04056,24.625,-23.3153 C:/Users/sh/AppData/Local/Temp/Slicer/BAEIE_vtkMRMLScalarVolumeNodeB.nrrd C:/Users/sh/AppData/Local/Temp/Slicer/BAEIE_vtkMRMLLabelMapVolumeNodeB.nrrd STANDARD
[DEBUG][Qt] 28.11.2017 06:44:30 [] (unknown:0) - Airway Segmentation CLI completed without errors
[INFO][VTK] 28.11.2017 06:44:31 [vtkMRMLVolumeArchetypeStorageNode (000001F512A72600)] (D:\D\P\Slicer-480\Libs\MRML\Core\vtkMRMLVolumeArchetypeStorageNode.cxx:465) - Loaded volume from file: C:/Users/sh/AppData/Local/Temp/Slicer/BAEIE_vtkMRMLLabelMapVolumeNodeB.nrrd. Dimensions: 512x512x249. Number of components: 1. Pixel type: unsigned short.

Regards
Ashly

**Comment by PietroNardelli** [comment]
The CLI module would not show the 3D model in the 3D viewer. Only the AirwaySegmentation module does it automatically. If you want to visualize the 3D model in the 3D viewer starting from the label created by the CLI module, you can use the Model Maker module available in Slicer. There you just need to specify the airway label created previously and the 3D model will be created and shown on the 3D viewer. Let me know if this works for you!

**Comment by ashlyshaji** [comment]
Dear Pietro,
Thank you so much . It works now..... 
Is it possible to use Airway Segmentation module directly for rendering, instead of using both Airway segmentation CLI and Model Maker Module??


![image](https://user-images.githubusercontent.com/34036397/33340155-9d275dcc-d47b-11e7-8d71-33f3b17daa20.png)

Best Regards
Ashly

**Comment by tresa7** [comment]
Dear Pietro,
I am a newbie to 3D slicer. As mentioned in the previous discussion , i tried both the airway segmentation CLI and Model Maker modules to reconstruct a 3D trans bronchial model from DICOM CT image.On clicking Apply button( Airway segmentation CLI) , the program is running ,but not getting 
 any label map.
The Dicom tag ( in Microdicom viewer) shows following details
image type                              DERIVED\SECONDARY\MPR
ManufacturerModelName	Brilliance 64,Philips
ConvolutionKernel           	L

I have used another set of DICOM images with following Dicom tag data.
image  type                             ORIGINAL\PRIMARY\AXIAL.
ManufacturerModelName	LightSpeed Ultra,GE Medical
And it works fine with both extension.

Could you please help me to rectify the problem with first set of DICOM data. Is it because of using "Multiplanar reformation" image ??
All your help will be  highly appreciated Pietro .

**Comment by PietroNardelli** [comment]
Hello,

would you mind sending the DICOM file so that I can have a look?

**Comment by tresa7** [comment]
[Dicom.zip](https://github.com/PietroNardelli/Slicer-AirwaySegmentation/files/1728508/Dicom.zip)

Please find the data.

**Comment by PietroNardelli** [comment]
The problem is that this CT data is very "particular". It has 512 axial and 56 coronal slices, which is really weird for a CT scan. I'll try to see if I can modify the code to fit cases like this as well.

**Comment by tresa7** [comment]
Thank you the prompt response.
For the current version of the Airway segmentation CLI module, Could you please mention the criterias the source images should meet?

**Comment by tresa7** [comment]
​
 65052266.zip
<https://drive.google.com/file/d/1VVKMS9Bpzgo9vpLm6TCEm2Zr1hzIWjJa/view?usp=drive_web>
​Dear Pietro,
I have tired airway segmentation CLI in another set of DICOM data, having
308 sagittal and 512 coronal and axial images, with no success.
The only problem I could figure out is the image type.
I have attached the images as a google drive link.

Could you please help me with the following queries:
1)Should we use "ORIGINAL\PRIMARY\AXIAL" for the segmentation module( as it
works in my case)
2) Is it okay to use " DERIVED\SECONDARY\MPR" for the module?

Thanks in advance

**Comment by PietroNardelli** [comment]
Hi Tresa,

The module was built to work with standard chest CT scans, meaning the ‘ORIGINAL\PRIMARY\AXIAL’ you are referring to, with shape 512x512xN. Currently the MPR reconstruction is not supported, but I am hoping to find time to work on that. 

Hope this helps!

Pietro

**Comment by tresa7** [comment]
Dear Pietro,
That clears up the doubts I had.
Thank you so much for your prompt response again.
Regards,
Tresa

**Comment by PietroNardelli** [comment]
You are welcome!  Let me know if I can help with anything else.

**Comment by tresa7** [comment]
Sure....

**Comment by stephamack31** [comment]
Hi Pietro,
I am trying to use the AirwaySegmentation module on 4.6.2 and it is throwing me this error 

"Exception!
Please use a DICOM image as input. For other image types, please use the Airway Segmentation CLI module."

<img width="640" alt="slicererror" src="https://user-images.githubusercontent.com/37884045/38060721-8862d1c0-32b1-11e8-9000-a48211411bef.PNG">

I am definitely using DICOM images. Any tips?

**Comment by PietroNardelli** [comment]
Hello! This is weird...let me look into it and I'll get back to you!

**Comment by PietroNardelli** [comment]
Anyway, if you know the image kernel type you can always use the AirwaySegmentation CLI module!

**Comment by andrew-berger** [comment]
Good afternoon Pietro Nardelli,

Thank you for all the information that you have already shared on this thread. I am trying to compare the difference in airflow pre and post tracheal stent surgery for CFD analysis with ANSYS. 

I believe that the Airway Segmentation or CLI module would provide the most consistent results for two different CT scans. I have tried other segmentation methods as well (Threshold, Grow from seeds, Fill between slices, Chest Imaging Platform, Vascular Modeling Toolkit). 

Following your steps, I cannot capture the full trachea using Airway Segmentation CLI module with either scan.
-	OS: Windows 64 bit, Intel Core i7 CPU @ 2.60GHz, 8.00 GB RAM
-	Version: Slicer 4.8.1, 4.9.0 (nightly build 7/2/18)

I was hoping you could help.

The pre-surgery file: (size 512x512 - uncertain)
https://drive.google.com/file/d/1cFc_9laXuk3aoe_OsSKvuT46TbUXKGoZ/view?usp=sharing

My results:
![image](https://user-images.githubusercontent.com/40803773/42237104-d121f4f8-7eca-11e8-95e9-235a6933a52d.png)

**Comment by jvwilliams23** [comment]
I am having the same issue as the original poster on Slicer 4.10.1. Using the main seed point I can only segment the trachea and main bronchi. 
Is this an issue with the algorithm you are aware of (if you still work on it)?

**Comment by jvwilliams23** [comment]
I can provide further insight on my case and files if desired

**Comment by andrew-berger** [comment]
Josh,

Unfortunately, I was unable to get a trachea segmentation that I was happy with. I am no longer working on that research. Hopefully, Pietro can offer some insight.

Good luck,

Andrew
